BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Addresses] (
    [AddressID] INT NOT NULL IDENTITY(1,1),
    [CartID] INT NOT NULL,
    [AddressLine1] NVARCHAR(255) NOT NULL,
    [AddressLine2] NVARCHAR(255),
    [City] NVARCHAR(100) NOT NULL,
    [State] NVARCHAR(100) NOT NULL,
    [ZipCode] NVARCHAR(20) NOT NULL,
    CONSTRAINT [PK__Addresse__091C2A1BC416867A] PRIMARY KEY CLUSTERED ([AddressID])
);

-- CreateTable
CREATE TABLE [dbo].[CartItems] (
    [CartItemID] INT NOT NULL IDENTITY(1,1),
    [CartID] INT NOT NULL,
    [ProductID] INT NOT NULL,
    [Quantity] INT NOT NULL,
    CONSTRAINT [PK__CartItem__488B0B2A17702A5D] PRIMARY KEY CLUSTERED ([CartItemID])
);

-- CreateTable
CREATE TABLE [dbo].[Carts] (
    [CartID] INT NOT NULL IDENTITY(1,1),
    [CreatedAt] DATETIME CONSTRAINT [DF__Carts__CreatedAt__3F466844] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME CONSTRAINT [DF__Carts__updatedAt__403A8C7D] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [PK__Carts__51BCD7973259E00D] PRIMARY KEY CLUSTERED ([CartID])
);

-- CreateTable
CREATE TABLE [dbo].[Orders] (
    [OrderID] INT NOT NULL IDENTITY(1,1),
    [CartID] INT NOT NULL,
    [OrderDate] DATETIME CONSTRAINT [DF__Orders__OrderDat__412EB0B6] DEFAULT CURRENT_TIMESTAMP,
    [TotalAmount] DECIMAL(10,2),
    CONSTRAINT [PK__Orders__C3905BAF64DB5BBF] PRIMARY KEY CLUSTERED ([OrderID])
);

-- CreateTable
CREATE TABLE [dbo].[Products] (
    [ProductID] INT NOT NULL IDENTITY(1,1),
    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(max),
    [Price] DECIMAL(10,2) NOT NULL,
    [Stock] INT NOT NULL,
    [CreatedAt] DATETIME CONSTRAINT [DF__Products__Create__4222D4EF] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME CONSTRAINT [DF__Products__update__4316F928] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [PK__Products__B40CC6ED8752482F] PRIMARY KEY CLUSTERED ([ProductID])
);

-- CreateTable
CREATE TABLE [dbo].[Users] (
    [UserID] INT NOT NULL IDENTITY(1,1),
    [Email] VARCHAR(50) NOT NULL,
    [Password] VARCHAR(max) NOT NULL,
    [Name] VARCHAR(50) NOT NULL,
    [Role] VARCHAR(50) NOT NULL,
    [CreatedAt] DATETIME CONSTRAINT [DF__Users__CreatedAt__4AB81AF0] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME CONSTRAINT [DF__Users__updatedAt__4BAC3F29] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserID])
);

-- AddForeignKey
ALTER TABLE [dbo].[Addresses] ADD CONSTRAINT [FK__Addresses__CartI__440B1D61] FOREIGN KEY ([CartID]) REFERENCES [dbo].[Carts]([CartID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CartItems] ADD CONSTRAINT [FK__CartItems__CartI__44FF419A] FOREIGN KEY ([CartID]) REFERENCES [dbo].[Carts]([CartID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CartItems] ADD CONSTRAINT [FK__CartItems__Produ__45F365D3] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Products]([ProductID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[Orders] ADD CONSTRAINT [FK__Orders__CartID__46E78A0C] FOREIGN KEY ([CartID]) REFERENCES [dbo].[Carts]([CartID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
